blank_issues_enabled: true
contact_links:
  - name: Security Vulnerabilities
    url: https://github.com/mels0n/tabletop_scheduler/security/policy
    about: Please report security vulnerabilities here.

